# Generated by Django 4.2.30 on 2026-05-28 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_concept', models.TextField()),
                ('episode_number', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('script_summary', models.TextField()),
            ],
        ),
    ]
