# Generated by Django 4.2.30 on 2026-05-28 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('story_gen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('concept', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='script',
            name='series_concept',
        ),
        migrations.AddField(
            model_name='script',
            name='series',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='scripts', to='story_gen.series'),
            preserve_default=False,
        ),
    ]
